#!/bin/bash

# Check if the correct number of arguments is passed
if [ $# -ne 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Extract the arguments
file_path="$1"
ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$ip:~/"

# Check if the file transfer was successful
if [ $? -eq 0 ]; then
  echo "File '$file_path' successfully transferred to $username@$ip."
else
  echo "Error: Failed to transfer file '$file_path' to $username@$ip."
  exit 1
fi

