#!/usr/bin/env bash

# Install nginx
apt-get -y install nginx

# Start nginx
service nginx start

# Allow traffic on port 80 for nginx
ufw allow 'Nginx HTTP'

# Create a custom page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Restart nginx
service nginx restart

