#!/usr/bin/env bash

ssh ubuntu@54.173.93.73 -i ~/.ssh/school
mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0iLA/SWCG3i44DhLWDqtvoZBlaCsN4QAMNOToTPs/YTxVYvrbKasIJkrQYMZEC2LzaL+TBrA28BYjr7vEpPtAkB/0+krm55yaM/EFMN9l3FDzeKefoccqSH+dtkyh6X7EeiE16MFjYbeW80EFCF8tzFKKEi46kx310ImbWnpUt135yrxf4iksB8NRBMNqmyermrLjH21bz/71qf8EiiR1eBJCovKvvmho1MLCjlGcbij3duL8j0jDgpmoz4u4CElFI45XJTGbUGfZB/hm2zsd7N1GuklgZfW6ligvsxzhiWKdm3GLNmdg7ggS39Js7cjANGl5G2pG7CkiWs0/tCNsxVJKkGBK2R9ivccYJyeyhIIDT/Hhd41mzsOSyscktr6YK7nBI0xpKACWP/WGuWyLRiWU8WBf1ETj3GX/1w1Fj0fvIUjLL26O+vSAyWEaAA/rlYSixa1Wyyj+eT3wszDy3G04aNJjvaafh3JvtWQrkC1ta9D9yt6VsCs+F2rpquk= lx@DESKTOP-M5CRR14 >> ~/.ssh/authorized_keys
